### ISSUE TITLE
Is kubesphere v3.3.2 compatible with ks-jenkins v3.5.0-2.346.3 or v4.0.0-2.346.3

### ISSUE THREAD

**Issue by littlejiancc** [kubesphere/ks-jenkins#104]
When I updated the ks-jenkins image to v3.5.0-2.346.3, jenkins failed to start.

**Comment by chilianyi** [comment]
What is the error msg for jenkins.

If the message is error about ldap, you can fix it by modify yaml of deploy/devops-jenkins

```
            - name: CASC_JENKINS_CONFIG
              value: /var/jenkins_home/casc_configs/jenkins_user.yaml
```

**Comment by littlejiancc** [comment]
@chilianyi Thank you for your reply. It is exactly as you said. after adding this env, jenkins starts ok.
