### ISSUE TITLE
[devops] send mail failed with step mail

### ISSUE THREAD

**Issue by yudong2015** [kubesphere/ks-jenkins#105]
version: v3.5.0-2.346.3

plugin version:

[workflow-basic-steps-plugin](https://github.com/jenkinsci/workflow-basic-steps-plugin): workflow-basic-steps-2.22
[mailer-plugin](https://github.com/jenkinsci/mailer-plugin): 435.438.v5b_81173f5b_a_1

First: 
[Set the Email Server for KubeSphere Pipelines](https://www.kubesphere.io/docs/v3.4/devops-user-guide/how-to-use/pipelines/jenkins-email/)

Pipeline:
![image](https://github.com/kubesphere/ks-jenkins/assets/14155338/ce04d426-b01c-494f-94e4-0b1a62d24e23)

Error:
![E5EA68DF-FFFD-46D4-846D-77ADD99B6776](https://github.com/kubesphere/ks-jenkins/assets/14155338/b885bc52-b6a2-46a2-b0db-62412b6fc893)

**Comment by yudong2015** [comment]
Reason: the param RecipientType in **basic-steps.MailStep** is from javax.mail, but that in MimeMessageBuilder is from jakarta.mail.

**Comment by yudong2015** [comment]
same issue: 
https://github.com/kubesphere/kubesphere/issues/6113

**Comment by benjaminhuo** [comment]
4.1.2 临近 code freeze， 挪 issue 到 4.1.2 要说明一下原委和现在的进度、哪个客户的要求等。@yudong2015 @stoneshi-yunify

**Comment by yudong2015** [comment]
> 4.1.2 临近 code freeze， 挪 issue 到 4.1.2 要说明一下原委和现在的进度、哪个客户的要求等。@yudong2015 @stoneshi-yunify

@benjaminhuo 这个 issue 的情况是：昨天客户  鸿富锦精密电子 提出的问题，这个 issue 之前就遇到了，解决方法是升级 jenkins 里的3个相关插件的版本，这个改动比较小，就几行插件版本的改动，主要是测试工作多；升级插件版本我已经测试过两次了，剩下就是插件版本改好后制作个镜像就可以了，所以就把这个 issue 加的 4.1.2 了。

**Comment by benjaminhuo** [comment]
ok, 做好了打上 need-to-verify 的 tag，改一下 project 的状态

**Comment by zjpjly** [comment]
![image](https://github.com/user-attachments/assets/2960be44-7dc4-469d-bb17-b603a4202daa)
