### ISSUE TITLE
kubesphere/jenkins-ks:2.176.2 pull wrong

### ISSUE THREAD

**Issue by a943915349** [kubesphere/ks-jenkins#12]
Failed to pull image "kubesphere/jenkins-ks:2.176.2": rpc error: code = Unknown desc = Error response from daemon: pull access denied for kubesphere/jenkins-ks, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Failed to pull image "kubesphere/jenkins-ks:2.176.2": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/kubesphere/jenkins-ks/manifests/2.176.2: Get https://auth.docker.io/token?scope=repository%3Akubesphere%2Fjenkins-ks%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by LinuxSuRen** [comment]
This image has not been released. If you want to try. Please take `kubespheredev/ks-jenkins:2.176.2`

**Comment by a943915349** [comment]
> This image has not been released. If you want to try. Please take `kubespheredev/ks-jenkins:2.176.2`

Thank you so much for your reply so soon，I installed it according to the official website 3.0 document，When will it be released

**Comment by a943915349** [comment]
And my kubesphere/kubectl:v1.17.0 haven't found the corresponding version on dockerhub, haven't it been released yet？

**Comment by LinuxSuRen** [comment]
> > This image has not been released. If you want to try. Please take `kubespheredev/ks-jenkins:2.176.2`
> 
> Thank you so much for your reply so soon，I installed it according to the official website 3.0 document，When will it be released

Would you please tell me the document link? I believe that might be a mistake.

**Comment by LinuxSuRen** [comment]
> And my kubesphere/kubectl:v1.17.0 haven't found the corresponding version on dockerhub, haven't it been released yet？

I'm not sure about this part. I see you already filed an issue [on there](https://github.com/kubesphere/kubectl/issues/2).

**Comment by a943915349** [comment]
> > And my kubesphere/kubectl:v1.17.0 haven't found the corresponding version on dockerhub, haven't it been released yet？
> 
> I'm not sure about this part. I see you already filed an issue [on there](https://github.com/kubesphere/kubectl/issues/2).

yes,that's my issue yesterday,

this is the link:https://kubesphere.io/docs/installing-on-kubernetes/introduction/overview/
~~~
kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.0.0/kubesphere-installer.yaml
kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.0.0/cluster-configuration.yaml
~~~
i set the devops:enabled:true

**Comment by LinuxSuRen** [comment]
Thanks for telling me the document link. But I still feel confused about the image. I have no idea why you can get `kubesphere/jenkins-ks:2.176.2`.

**Comment by a943915349** [comment]
> Thanks for telling me the document link. But I still feel confused about the image. I have no idea why you can get `kubesphere/jenkins-ks:2.176.2`.

i dont know why i have this error,i can give u my kubesphere-installer.yaml , cluster-configuration.yaml and some image tonight when i back home,can u give me some suggestion,thanks a lot

**Comment by LinuxSuRen** [comment]
Hopefully, we can find some clues from those config files.

**Comment by a943915349** [comment]
> Hopefully, we can find some clues from those config files.

thank u so much,and i'm a  beginner for study kubernetes,when i find kubesphere,i'm appreciate and pround for yours product,
I really hope it gets better and better

**Comment by a943915349** [comment]
> > Hopefully, we can find some clues from those config files.
> 
> thank u so much,and i'm a beginner for study kubernetes,when i find kubesphere,i'm appreciate and pround for yours product,
> I really hope it gets better and better

![1](https://user-images.githubusercontent.com/44340137/101175686-6c8fa880-3680-11eb-8780-5627df9c9994.png)
![2](https://user-images.githubusercontent.com/44340137/101175704-73b6b680-3680-11eb-9f69-6aa8ee6d26d9.png)
![3](https://user-images.githubusercontent.com/44340137/101175718-76b1a700-3680-11eb-963e-0c2b8cef104d.png)

pic and yaml: [https://github.com/a943915349/kubesphere](url)

**Comment by LinuxSuRen** [comment]
The problem might caused the config file [kubesphere-installer.yaml](https://github.com/a943915349/kubesphere/blob/master/kubesphere-installer.yaml).

Please see [kubesphere-installer.yaml#L236](https://github.com/a943915349/kubesphere/blob/254bfabe60736394972667955b0239c70509c204/kubesphere-installer.yaml#L236)

`kubespheredev/xxx` is not a released image.

If you want to install a released Kubesphere instead of trying some new features, please make sure to follow this document.
https://kubesphere.io/docs/installing-on-kubernetes/introduction/overview/. And don't replace any docker image path.

Of course, welcome to deep into Kuberesphere.

I guess we can close this issue. The document should be correct.

**Comment by a943915349** [comment]
> The problem might caused the config file [kubesphere-installer.yaml](https://github.com/a943915349/kubesphere/blob/master/kubesphere-installer.yaml).
> 
> Please see [kubesphere-installer.yaml#L236](https://github.com/a943915349/kubesphere/blob/254bfabe60736394972667955b0239c70509c204/kubesphere-installer.yaml#L236)
> 
> `kubespheredev/xxx` is not a released image.
> 
> If you want to install a released Kubesphere instead of trying some new features, please make sure to follow this document.
> https://kubesphere.io/docs/installing-on-kubernetes/introduction/overview/. And don't replace any docker image path.
> 
> Of course, welcome to deep into Kuberesphere.
> 
> I guess we can close this issue. The document should be correct.

ok
thank u so much,i'll reset it
