### ISSUE TITLE
Integrate metersphere to KubeSphere DevOps

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/ks-jenkins#17]
https://metersphere.io/

**Comment by LinuxSuRen** [comment]
I found a video which introduce how to integrate Jenkins with MeterSphere. https://www.bilibili.com/video/BV1yy4y1S75X

**Comment by shaowenchen** [comment]
https://kubesphere.com.cn/forum/d/3460-kubesphere-metersphere
https://kubesphere.com.cn/forum/d/3484-kubesphere-devops-metersphere
