### ISSUE TITLE
Request to support Jenkins ANSI Color Plugin

### ISSUE THREAD

**Issue by Feeeenng** [kubesphere/ks-jenkins#40]
## Plugin Name
`ansiColor`
## Plugin Url
https://plugins.jenkins.io/ansicolor/

## Reasons support
Provide terminal display in different colors. In the face of log troubleshooting, it is very helpful

**Comment by JohnNiang** [comment]
/retitle Request to support Jenkins ANSI Color Plugin

**Comment by LinuxSuRen** [comment]
I guess you try to check the log output from Jenkins. But We don't intend to let users use Jenkins console directly. Jenkins is just a backend of the CI engine.

If you wish have a better color scheme of the Pipeline log output. Please file an issue in project [kubesphere/console](https://github.com/kubesphere/console/issues).

Any way. Thanks for reaching to us.

/close
